const List<String> charadesWords = [
  'Giraffe', 'Elephant', 'Penguin', 'Dolphin', 'Kangaroo', 'Octopus', 'Butterfly',
  'Panda', 'Peacock', 'Chameleon', 'Flamingo', 'Hedgehog', 'Jellyfish', 'Koala',
  'Lion', 'Monkey', 'Owl', 'Parrot', 'Rabbit', 'Tiger', 'Turtle', 'Zebra',
  'Pizza', 'Burger', 'Sushi', 'Pasta', 'Ice Cream', 'Pancake', 'Popcorn',
  'Watermelon', 'Chocolate', 'Donut', 'Taco', 'Sandwich', 'French Fries',
  'Basketball', 'Football', 'Swimming', 'Cycling', 'Tennis', 'Volleyball',
  'Baseball', 'Cricket', 'Badminton', 'Table Tennis', 'Karate', 'Boxing',
  'Guitar', 'Piano', 'Drums', 'Violin', 'Microphone', 'Headphones', 'Concert',
  'Disney', 'Superman', 'Batman', 'Spider Man', 'Frozen', 'Harry Potter',
  'Star Wars', 'Avatar', 'Minions', 'Shrek', 'Toy Story', 'Finding Nemo',
  'The Lion King', 'Moana', 'Coco', 'Encanto', 'Incredibles', 'Despicable Me',
  'Beach', 'Mountain', 'Forest', 'Desert', 'Waterfall', 'Volcano', 'Island',
  'Rainbow', 'Sunset', 'Thunderstorm', 'Snowflake', 'Earthquake', 'Tornado',
  'Astronaut', 'Rocket', 'Telescope', 'Planet', 'Moon', 'Sun', 'Constellation',
  'Doctor', 'Teacher', 'Chef', 'Firefighter', 'Pilot', 'Scientist', 'Artist',
  'Photographer', 'Detective', 'Veterinarian', 'Engineer', 'Astronaut',
  'Camera', 'Telephone', 'Computer', 'Television', 'Radio', 'Robot', 'Drone',
  'Refrigerator', 'Microwave', 'Vacuum Cleaner', 'Washing Machine', 'Clock',
  'Bicycle', 'Helicopter', 'Submarine', 'Hot Air Balloon', 'Spaceship',
  'Castle', 'Lighthouse', 'Skyscraper', 'Tent', 'Treehouse', 'Igloo',
  'Birthday', 'Wedding', 'Circus', 'Carnival', 'Festival', 'Parade',
  'Dragon', 'Unicorn', 'Mermaid', 'Fairy', 'Wizard', 'Vampire', 'Zombie',
  'Ghost', 'Werewolf', 'Alien', 'Phoenix', 'Yeti', 'Kraken', 'Hydra',
  'Sunglasses', 'Umbrella', 'Crown', 'Backpack', 'Watch', 'Wallet',
  'Ladder', 'Rope', 'Flashlight', 'Compass', 'Magnifying Glass', 'Key',
  'Diamond', 'Emerald', 'Ruby', 'Sapphire', 'Gold', 'Silver', 'Pearl',
  'Rainbow', 'Tornado', 'Hurricane', 'Blizzard', 'Drought', 'Flood',
  'Coffee', 'Tea', 'Milk', 'Juice', 'Lemonade', 'Milkshake', 'Smoothie',
  'Great Wall of China', 'Eiffel Tower', 'Pyramids', 'Taj Mahal', 'Statue of Liberty',
  'Big Ben', 'Sydney Opera House', 'Christ the Redeemer', 'Machu Picchu',
  'Painting', 'Sculpture', 'Ballet', 'Opera', 'Theater', 'Movie',
  'Tattoo', 'Trophy', 'Medal', 'Ribbon', 'Flag', 'Map', 'Globe',
  'Candle', 'Lantern', 'Bonfire', 'Fireworks', 'Torch', 'Match',
  'Librarian', 'Gardener', 'Fisherman', 'Farmer', 'Builder', 'Painter',
  'Dancing', 'Singing', 'Cooking', 'Drawing', 'Reading', 'Sleeping',
  'Whisper', 'Laugh', 'Cry', 'Yawn', 'Sneeze', 'Cough', 'Snore',
  'Volleyball', 'Badminton', 'Archery', 'Fencing', 'Wrestling', 'Judo',
  'Trampoline', 'Skateboard', 'Rollerblade', 'Scooter', 'Sled', 'Surfing',
  'Skiing', 'Snowboarding', 'Ice Skating', 'Rock Climbing', 'Zip Line',
  'Camping', 'Fishing', 'Hiking', 'Picnic', 'Road Trip', 'Safari',
  'Origami', 'Kite', 'Yo Yo', 'Jigsaw Puzzle', 'Rubik Cube', 'Domino',
  'Sword', 'Shield', 'Bow and Arrow', 'Cannon', 'Armor', 'Throne',
  'Necklace', 'Bracelet', 'Earring', 'Ring', 'Tiara', 'Brooch',
  'Camel', 'Horse', 'Cow', 'Sheep', 'Goat', 'Donkey', 'Pig', 'Chicken',
  'Duck', 'Turkey', 'Goose', 'Swan', 'Eagle', 'Hawk', 'Crow', 'Parrot',
  'Great Wall', 'Northern Lights', 'Grand Canyon', 'Amazon River', 'Sahara Desert',
  'Niagara Falls', 'Mount Everest', 'Dead Sea', 'Bermuda Triangle', 'Stonehenge',
  'Volcano', 'Geyser', 'Cave', 'Glacier', 'Oasis', 'Reef', 'Lagoon',
  'Pirate', 'Ninja', 'Samurai', 'Knight', 'Cowboy', 'Viking', 'Pharaoh',
  'Fossil', 'Dinosaur', 'Mammoth', 'Saber Tooth', 'Pterodactyl', 'Triceratops',
  'Stegosaurus', 'Brachiosaurus', 'Velociraptor', 'Pterosaur', 'Ichthyosaur',
];
